spring:
  mail:
    host: smtp.gmail.com
    username: v4431365@gmail.com
    password: iponuhntztqltauh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true